twitter:
  consumer_key: rizxIZ5tWC8TEUNElLD8Cw
  consumer_secret: 9F0rSBayH73x6J0dmyxtNvokl59Yv1yjoCf33bs
  oauth_token: 7256962-88V7NhDNtqADDXAbQBqiU09jmwMZwL1aDhjiP9yU
  oauth_token_secret: oJiMVAHJehXtp54aEFFv2wRY6iIycs5lOKER3LNo